name=input("Enter Your Name \n")
crush=input("Crush Name \n")
import turtle
t=turtle.Turtle()
turtle.bgcolor('black')
t.begin_fill()
t.color('red','red')
t.left(50)
t.forward(133) 
t.circle(50,200)
t.right(140)
t.circle(50,200)
t.forward(133)
t.speed(1)
turtle.bgcolor('black')
t.end_fill()
t.penup()
t.goto(-299,200)
t.pendown()
t.color('orange')
t.write(name, font=('courier',50))
t.penup()
t.goto(-250,-160)
t.pendown()
t.color('orange')
t.write(crush, font=('courier',50))      
turtle.done()



# name=input("What is your name? \n")

# colour=input("What is favourite colour\n")
# print(name + " likes " + colour)
# from turtle import*
# begin_fill()
# color("pink",colour)
# pensize(5)
# speed(1)
# left(50)
# forward(113)
# circle(50,200)
# right(140)
# circle(50,200)
# forward(133)
# end_fill()
# # for i in range(7):
# #     begin_fill()
# #     color("pink",colour)
# #     pensize(5)
# #     left(50)
# #     forward(113)
# #     circle(50,200)
# #     right(140)
# #     circle(50,200)
# #     forward(133)
# #     end_fill()

# hideturtle()


# import turtle
# t=turtle.Turtle()
# turtle.bgcolor('black')
# t.color('blue')
# t.forward(100)
# t.write('HELLO!! ',font=('courier',100,'bold')) 
# t.right(100)
# turtle.speed(333)
# turtle.bgcolor('red')
# for i in range(1,11):
#     x=input("Enter name")
    
#     turtle.bgcolor('aqua')
#     t.color('blue')
#     t.forward(100)
#     t.right(100)
#     turtle.bgcolor('pink')
# t.penup()
# t.right(100)
# t.forward(500)
# t.pendown()    

# t.write('BEY!! ',font=('courier',100,'bold'))    
# turtle.done()

# from turtle import* 
# bgcolor('skyblue')
# speed(0)
# hideturtle()
# for i in range(120):
#     bgcolor('red')
#     circle(i)
#     circle(i*0.8)
#     right(3)
#     bgcolor('orange')
#     forward(3)
    
# done()